GLASSFISH-19688: Don't explode OSGi applications in tmpdir
This is a follow up to the earlier fix done by Tang in rev #60755. After that fix, 
we started getting NullPointerException during server restart:

[2013-03-25T22:22:20.980+0530] [glassfish 4.0] [WARNING] [] [org.glassfish.osgijavaeebase] [tid: _ThreadID=91 _ThreadName=pool-15-thread-1] [timeMillis: 1364230340980] [levelValue: 900] [[
  Failed to deploy bundle org.glassfish.fighterfish.sample.uas.simplewab [293]
org.glassfish.osgijavaeebase.DeploymentException: Deployment of org.glassfish.fighterfish.sample.uas.simplewab [293] failed because of following reason: Failed while deploying bundle org.glassfish.fighterfish.sample.uas.simplewab [293] : java.lang.NullPointerException
    at org.glassfish.osgijavaeebase.AbstractOSGiDeployer.deploy(AbstractOSGiDeployer.java:127)
    at org.glassfish.osgijavaeebase.OSGiContainer.deploy(OSGiContainer.java:154)
    at org.glassfish.osgijavaeebase.JavaEEExtender.deploy(JavaEEExtender.java:109)
    at org.glassfish.osgijavaeebase.JavaEEExtender.access$200(JavaEEExtender.java:61)
    at org.glassfish.osgijavaeebase.JavaEEExtender$HybridBundleTrackerCustomizer$1.call(JavaEEExtender.java:153)
    at org.glassfish.osgijavaeebase.JavaEEExtender$HybridBundleTrackerCustomizer$1.call(JavaEEExtender.java:150)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
    at java.io.File.<init>(File.java:389)
    at org.glassfish.deployment.common.DeploymentContextImpl.getSourceDir(DeploymentContextImpl.java:305)
    at org.glassfish.osgiweb.OSGiWebDeploymentContext$WABClassLoader.<init>(OSGiWebDeploymentContext.java:213)
    at org.glassfish.osgiweb.OSGiWebDeploymentContext.setupClassLoader(OSGiWebDeploymentContext.java:124)
    at org.glassfish.osgijavaeebase.OSGiDeploymentContext.<init>(OSGiDeploymentContext.java:77)
    at org.glassfish.osgiweb.OSGiWebDeploymentContext.<init>(OSGiWebDeploymentContext.java:91)
    at org.glassfish.osgiweb.OSGiWebDeploymentRequest.getDeploymentContextImpl(OSGiWebDeploymentRequest.java:96)
    at org.glassfish.osgijavaeebase.OSGiDeploymentRequest.prepare(OSGiDeploymentRequest.java:158)
    at org.glassfish.osgijavaeebase.OSGiDeploymentRequest.execute(OSGiDeploymentRequest.java:119)
    at org.glassfish.osgijavaeebase.AbstractOSGiDeployer.deploy(AbstractOSGiDeployer.java:123)
    ... 10 more
]]

This NPE happens when there is an exploded directory already present when server is started. 
An exploded directory can exist for various reasons including the scenario described in GLASSFISH-19697.
In such a case, our new code was not setting archive object to represent the exploded directory.
Since archive is by default set to WAB whose getSource() returns null, we get NPE.

The fix made here is to ensure that we clean up existing directory. For various reasons mentioned in code,
we can't safely reuse an existing directory, so we delete it and go through the same code as if it's first time
deployment.

svn path=/trunk/fighterfish/; revision=60803